### ISSUE TITLE
Начальный баланс счета при пополнении на сумму, не превышающую  величину максимального баланса, равен сумме пополнения.

### ISSUE THREAD

**Issue by OlgaUsh89** [EkaterinaEv/javaqa-team-diplom-2#1]
# Описание
При пополнении счета на сумму, не превышающую максимальный лимит, баланс равен сумме пополнения.

# Локация дефекта
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/3d101845859fa44f1253ff2cd3aa40b9ccff8378/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыт [код программы](https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/3d101845859fa44f1253ff2cd3aa40b9ccff8378/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68) в IDEA.
2. Выставить значение переменной 'inicialBalance' в 2000
3. Выставить значение переменной 'minBalance' в 1000
4. Выставить значение переменной 'maxBalance' в 10000
5. Выставить значение переменной 'rate' в 5
6. Выставить значение переменной 'amount' в 3000
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс счета 5000
*Факический результат:* Баланс равен сумме пополнения (3000)

# Тестирование бага
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/54da57b5e96d28511ec304b486d2013d4413eead/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L20

# Скриншот
![image](https://github.com/EkaterinaEv/javaqa-team-diplom-2/assets/135870753/aab1b61f-e380-46dc-8406-bf32cb7f8a4a)

# Окружение
*  **Операционная система :** Windows 10
*  **IDE:** IntelliJ IDEA 2020.2(Community Edition)
*  **Java:** OpenJDK 11

**Comment by EkaterinaEv** [comment]
*Внесены исправления в метод пополнения счета*
