### ISSUE TITLE
При сумме покупки, превышающей начальный баланс, счет уходит в минус.

### ISSUE THREAD

**Issue by OlgaUsh89** [EkaterinaEv/javaqa-team-diplom-2#2]
# Описание
При оплате на сумму, которая превышает начальный баланс, счет уходит в минус (должен не меняться).

# Локация дефекта
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/3d101845859fa44f1253ff2cd3aa40b9ccff8378/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1.Открыть [код программы](https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/3d101845859fa44f1253ff2cd3aa40b9ccff8378/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44) в IDEA
2.Выставить значение переменной 'initialBalance' в 2000.
3.Выставить значение переменной 'minBalance' в 1000.
4.Выставить значение переменной 'maxBalance' в 10_000.
5.Выставить значение переменной 'rate' (процентная ставка) в 5.
6.Выставить значение переменной 'amount' в 10000.
7.Запустить тест.
8.Посмотреть на вывод в консоли.

*Ожидаемый результат:* баланс равен 2000.
*Фактический результат:* сумма баланса -8000

# Тестирование бага
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/54da57b5e96d28511ec304b486d2013d4413eead/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L81-L87

# Скриншот
![image](https://github.com/EkaterinaEv/javaqa-team-diplom-2/assets/135870753/78021fd6-7edc-4a29-8aa3-8d6a31937586)

# Окружение
*  **Операционная система:** Windows 10;
*  **IDE:**  IntelliJ IDEA 2020.2 (Community Edition)
*  **Java:**  OpenJDK 11

**Comment by EkaterinaEv** [comment]
*Внесены исправления в метод оплаты*
