### ISSUE TITLE
При отрицательном балансе на счете производится расчет процентов на остаток счета

### ISSUE THREAD

**Issue by OlgaUsh89** [EkaterinaEv/javaqa-team-diplom-2#3]
# Описание
Расчет процентов на остаток по счету производится при отрицательном балансе.

# Локация дефекта
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/3d101845859fa44f1253ff2cd3aa40b9ccff8378/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1.Открыть [код программы](https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/3d101845859fa44f1253ff2cd3aa40b9ccff8378/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88) в IDEA
2.Выставить значение переменной 'initialBalance' в -2000.
3.Выставить значение переменной 'minBalance' в 1000.
4.Выставить значение переменной 'maxBalance' в 10_000.
5.Выставить значение переменной 'rate' (процентная ставка) в 5.
6.Запустить тест.
7.Посмотреть на вывод в консоли.

*Ожидаемый результат:* баланс равен 0.
*Фактический результат:* сумма баланса -100

# Тестирование бага
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/54da57b5e96d28511ec304b486d2013d4413eead/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L97-L103

# Скриншот
![image](https://github.com/EkaterinaEv/javaqa-team-diplom-2/assets/135870753/af3ae33e-102c-4934-a673-0dc81e339248)

# Окружение
*  **Операционная система:** Windows 10;
*  **IDE:**  IntelliJ IDEA 2020.2 (Community Edition)
*  **Java:**  OpenJDK 11

**Comment by EkaterinaEv** [comment]
*Внесены исправления в метод расчета процентов на остаток счета*
