### ISSUE TITLE
При пополнении баланса, имеющего положительное значение, итоговый баланс равен сумме пополнения.

### ISSUE THREAD

**Issue by EkaterinaEv** [EkaterinaEv/javaqa-team-diplom-2#4]
# Описание

Если начальный баланс счета > 0, то итоговый баланс равен сумме пополнения.

# Локация дефекта

https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/7cdcc365cd3b1ed4156e22bef16b9fe30a0e2171/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Выставить значение переменной initialBalance =300
3. Выставить значение переменной creditLimit =5000
4. Выставить значение переменной rate= 15
5. Выставить значение переменной amount= 3000
6. Запустить программу
7. Посмотреть вывод в консоли

*Ожидаемый результат:* Баланс счета = 3300
*Фактический результат:* Баланс счета = 3000 (сумме пополнения)

# Тестирование бага
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/7cdcc365cd3b1ed4156e22bef16b9fe30a0e2171/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L9-L18

# Скриншот

![1](https://github.com/EkaterinaEv/javaqa-team-diplom-2/assets/135538938/a54ae998-3b23-434d-9be2-cb1efca7200e)

# Окружение
* **Операционная система:** Windows 10 Версия 112.0.5615.138 (Официальная сборка), (64 бит)
* **IDE:** IntelliJ IDEA Community Edition 2023.2
* **JAVA:** Open JDK 11е

**Comment by OlgaUsh89** [comment]
Ошибка крылась в строке balance = amount;
