### ISSUE TITLE
При оплате с карты, баланс становится отрицательным, даже если текущий баланс больше суммы оплаты.

### ISSUE THREAD

**Issue by EkaterinaEv** [EkaterinaEv/javaqa-team-diplom-2#5]
# Описание

Если оплата > 0, то баланс карты становится отрицательным, даже если оплата не превышает
текущий баланс.

# Локация дефекта
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/7cdcc365cd3b1ed4156e22bef16b9fe30a0e2171/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Выставить значение переменной initialBalance = 300
3. Выставить значение переменной creditLimit = 5000
4. Выставить значение переменной rate = 15
5. Выставить значение переменной amount = 200
6. Запустить программу
7. Посмотреть вывод в консоли

*Ожидаемый результат:* Баланс счета =100
*Фактический результат:* Баланс счета = -200 

# Тестирование бага
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/7cdcc365cd3b1ed4156e22bef16b9fe30a0e2171/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L87-L96

# Скриншот
![2](https://github.com/EkaterinaEv/javaqa-team-diplom-2/assets/135538938/1821c23c-e963-4b8b-ad02-fde3ca62a129)

# Окружение
* **Операционная система:** Windows 10 Версия 112.0.5615.138 (Официальная сборка), (64 бит)
* **IDE:** IntelliJ IDEA Community Edition 2023.2
* **JAVA:** Open JDK 11е

**Comment by OlgaUsh89** [comment]
Ошибка крылась в строке balance = -amount; из-за чего результат всегда был отрицательным.
