### ISSUE TITLE
При положительном балансе производится расчет процентов.

### ISSUE THREAD

**Issue by EkaterinaEv** [EkaterinaEv/javaqa-team-diplom-2#6]
# Описание

Расчет процентов производится на положительный баланс.

# Локация дефекта
https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/7cdcc365cd3b1ed4156e22bef16b9fe30a0e2171/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Выставить значение переменной initialBalance = 200
3. Выставить значение переменной creditLimit = 5000
4. Выставить значение переменной rate = 15
5. Запустить программу
6. Посмотреть вывод в консоли 

*Ожидаемый результат:* проценты = 0
*Фактический результат:* проценты = 30

# Тестирование бага

https://github.com/EkaterinaEv/javaqa-team-diplom-2/blob/7cdcc365cd3b1ed4156e22bef16b9fe30a0e2171/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L128-L137

# Скриншот
![3](https://github.com/EkaterinaEv/javaqa-team-diplom-2/assets/135538938/c9250945-adf0-442d-864b-7907332edc8f)

# Окружение
* **Операционная система:** Windows 10 Версия 112.0.5615.138 (Официальная сборка), (64 бит)
* **IDE:** IntelliJ IDEA Community Edition 2023.2
* **JAVA:** Open JDK 11е

**Comment by OlgaUsh89** [comment]
Ошибка крылась в отсутсвии условия if (balance >= 0) {
            return 0;
